version = 0.1

[default.deploy.parameters]
stack_name = "hackagallery-backend"
resolve_s3 = true
s3_prefix = "hackagallery-backend"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["ProjectAnalysisFunction=767398133223.dkr.ecr.us-west-2.amazonaws.com/hackagallery-backend"]
confirm_changeset = false

[default.build.parameters]
use_container = true
