AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HackaGallery FastAPI Backend with Lambda Web Adapter (with Parameter Store)

Globals:
  Function:
    Timeout: 120
    MemorySize: 512

Resources:
  ProjectAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          AWS_REGION: us-west-2
          AGENT_RUNTIME_ARN: arn:aws:bedrock-agentcore:us-west-2:767398133223:runtime/main-4U1jMUFTtk
          CACHE_TTL: 3600
          API_TIMEOUT: 120
          # GitHub token from Parameter Store (secure)
          GITHUB_TOKEN: '{{resolve:ssm:/hackagallery/github-token:1}}'
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
            - POST
            - OPTIONS
          AllowHeaders:
            - "*"
          MaxAge: 300
      Policies:
        - Statement:
          - Sid: BedrockAgentCoreInvokePolicy
            Effect: Allow
            Action:
              - bedrock:InvokeAgent
              - bedrock-agent-runtime:InvokeAgent
            Resource: '*'
          - Sid: SSMParameterAccess
            Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: 
              - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/hackagallery/*'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

Outputs:
  ProjectAnalysisFunctionUrl:
    Description: "Function URL for Project Analysis API"
    Value: !GetAtt ProjectAnalysisFunctionUrl.FunctionUrl
  
  ProjectAnalysisFunction:
    Description: "Project Analysis Lambda Function ARN"
    Value: !GetAtt ProjectAnalysisFunction.Arn
