AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: HackaGallery FastAPI Backend with Lambda Web Adapter (with Parameter Store)

Globals:
  Function:
    Timeout: 120
    MemorySize: 512

Resources:
  ProjectAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          PROJECT_INTELLIGENCE_AGENT_ARN: arn:aws:bedrock-agentcore:us-west-2:767398133223:runtime/src_project_intelligence_agent-3ML6X3HpFG
          CACHE_TTL_SECONDS: 3600
          API_TIMEOUT_SECONDS: 120
          # GitHub token will be fetched from Parameter Store at runtime
          GITHUB_TOKEN_PARAM_NAME: "/hackagallery/github-token"
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - GET
            - POST
          AllowHeaders:
            - "*"
          MaxAge: 300
      Policies:
        - Statement:
            - Sid: BedrockAgentCoreInvokePolicy
              Effect: Allow
              Action:
                - bedrock-agentcore:InvokeAgentRuntime
              Resource: "*"
            - Sid: SSMParameterAccess
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/hackagallery/*"
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

Outputs:
  ProjectAnalysisFunctionUrl:
    Description: "Function URL for Project Analysis API"
    Value: !GetAtt ProjectAnalysisFunctionUrl.FunctionUrl

  ProjectAnalysisFunction:
    Description: "Project Analysis Lambda Function ARN"
    Value: !GetAtt ProjectAnalysisFunction.Arn
